spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book-review?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: topy
    password: 1234
    name: book-review

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true