### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "cgy7127@gmail.com",
  "password": "bar",
  "nickname": "nick"
}

### 로그인
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "email": "cgy7127@gmail.com",
  "password": "bar"
}

### 로그아웃
GET http://localhost:8080/auth/signout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjZ3k3MTI3QGdtYWlsLmNvbSIsImV4cCI6MTcwMzI1NzkzOCwiaWF0IjoxNzAzMjU0MzM4fQ.DP0xp3TP2mmlH5z-Fu58oElYJMDrmSpj_sDqvexduSI


