### SSE 연결 요청
GET http://localhost:8080/sse/connect
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjZ3k3MTI3QGdtYWlsLmNvbSIsImV4cCI6MTcwNTEwMjA2MCwiaWF0IjoxNzA1MDkxMjYwfQ.HcWh1tiSPfNHTZsc1MU0BL623bCZaJ5z5f8quhCqvp0